config/routes.rb
Rails.application.routes.draw do
  get 'authentication/login'
  post 'authentication/login'

  get 'authentication/welcome'
  post 'authentication/welcome'

  get 'authentication/error'
  post 'authentication/error'

  get 'authentication/navigate'
	post 'authentication/navigate'

	get 'authentication/files'
  post 'authentication/files'

	get 'authentication/navigation_params'
	post 'authentication/navigation_params'

  post 'upload' => 'authentication#upload'

  get 'refresh' => 'authentication#refresh'

  post 'rename' => 'authentication#refresh'

  post 'move' => 'authentication#move'

  post 'remove' => 'authentication#remove'
  
  get 'login1' => 'sessions#new'

  post 'sessions/create'
  
  get 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  
  get 'error' => 'sessions#error'

  root 'authentication#login'

end

app/controllers/authentication_controller.rb
require 'rubygems'
require 'mechanize'
require 'dropbox_sdk'
require 'uri'
require 'net/http'
require 'json'

# @author Mauro Victor
class AuthenticationController < ApplicationController
# Class that control the Authenticatiom system and its views
  
  layout 'login', :only => [:login]
  
  include AuthenticationHelper #Use this module of helpers
  
  APP_KEY = '1g9mnjegs1l7j3m'
  APP_SECRET = 'glhnoqva181wmpa'

  def welcome
    $client = DropboxClient.new("siZpe-o98xoAAAAAAAAAl9HJEsrdDz0EPFebqJHr-oZryn0TL2aNhcGVSQvEjm71")
  end

  def files(search=params[:search])
    if search == nil 
      @archives = Archive.where({show: true, path: session[:dbox_path]})
    else
      files_list = Archive.all.pluck(:name)
      search_list = Array.new
      files_list.each do |f|
        search_list << f.to_s if f.to_s.include?(search)
      end
      @archives = Archive.where({show: true, path: session[:dbox_path], name: search_list})
    end

  end

  def login 
    if current_user
      #request the expa's current user data
      @request = "https://gis-api.aiesec.org:443/v1/current_person.json?access_token=#{session[:token]}"
      resp = Net::HTTP.get_response(URI.parse(@request))
      data = resp.body
      @current_person = JSON.parse(data)
      #Find the user on system
      @user = User.find_by_email(params[:my_email])
      redirect_to authentication_welcome_path
    else
      render 'login'
    end
  end


  # Takes the params for navigation 
  # @param content [String] path of the actual directory
  # @param upload[String] upload file to be uploaded
  # @param new_folder_name [String] name of the new folder name in case the user fulfilled a form to create a new one
  # @param files_array [Array] array of files to check if the file to be uploaded alaready exists
  # @param rename [Array] new and old name from the file that will be renamed
  # @param move [Array] Origin path and target path for the file will be moved
  # @param page [Number] Number of the page passed by the user through it's navigation
  # @param remove [String] Path of file to be removed on the request
  def navigation_params (content=params[:parent_id])
    #Store the path into a global variable because this variable is necessary in others methods.
    #If it is being requested by Arquivos's link set the root as "/"
    if request.get?
      session[:dbox_path] = "/"
    else
      session[:dbox_path] = content
    end
    redirect_to authentication_files_path
  end

  def refresh 
    recs = Archive.all.pluck(:name)
    dbox_files = Array.new
    root_metadata = $client.metadata(session[:dbox_path])['contents']

    root_metadata.each do |file|
      unless Archive.find_by_name(file['path'].split('/').last)
        record = Archive.new
        record.name = file['path'].split('/').last
        record.path = session[:dbox_path]
        record.dir = file['is_dir']
        record.show = true
        record.save
      end
      dbox_files << file['path'].split('/').last 
    end

    recs.each do |rec|
      unless dbox_files.include?(rec)
        Archive.find_by_name(rec).destroy
      end
    end
    redirect_to authentication_files_path
  end
  
  def upload(upload=params[:file], path=params[:parent_id])
    unless upload == nil || Archive.find_by_name("#{upload.original_filename}")
      file = open(upload.path())
      response = $client.put_file("#{session[:dbox_path]}/#{upload.original_filename}", file)
      #Save a record with the data about who uploaded the file
      record = Archive.new
      record.name = upload.original_filename
      record.owner = current_user.name
      record.local_commitment = current_user.local_commitment
      record.path = path
      record.show = true
      record.dir = false
      record.save
    end
    redirect_to authentication_files_path
  end

  #def new_folder(new_folder=params[:folder_name])
  #  unless new_folder == nil
  #    $client.file_create_folder("#{session[:dbox_path]}/#{new_folder}")
  #    record = Archive.new
  #    record.name = new_folder
  #    record.path = session[:dbox_path]
  #    record.dir = true
  #    record.save
  #  end
  #  redirect_to authentication_files_path
  #end

  def rename(rename=[params[:rename_new_name], params[:rename_old_name]])
    unless rename[0] == nil
      $client.file_move("#{session[:dbox_path]}/#{rename[1]}","#{session[:dbox_path]}/#{rename[0]}")
      record = Archive.find_by_name(rename[1])
      record.name = rename[0]
      record.save
    end
    redirect_to authentication_files_path
  end

  def move(move=[params[:move_to], params[:move_from]])
    record = Archive.find_by_name(move[1])
    record.path = (session[:dbox_path] == "/") ? "/#{move[0]}/" : "#{session[:dbox_path]}/#{move[0]}/"
    record.save
    redirect_to authentication_files_path
  end

  def remove(remove=params[:to_remove])
    record = Archive.find_by_name(remove)
    record.show = false
    record.save
    redirect_to authentication_files_path
  end
  
  helper_method :current_user
  
  #define the current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    return @current_user
  end

  def require_user
    redirect_to '/login' unless $current_user
  end
  
  
end

app/helpers/authentication_helper.rb
module AuthenticationHelper


  def take_name(name)
    if name.scan("/").count >= 2
      name = name.split("/").last
    else
      name = name[1..-1]
    end
    name
  end

  def date_format(date)
    text = date.split("+").first
    text = text.split(" ")
    text = text[1..-1]
    month_hash = {"Jan" => 1, "Feb" => 2, "Mar" => 3, "Apr" => 4, "May" => 5, "Jun" => 6, "Jul" => 7, "Aug" => 8, "Sep" => 9, "Oct" => 10, "Nov" => 11, "Dec" => 12 }
    month = month_hash[text[1]]
    date = "#{text[0]}/#{month}/#{text[2]}, #{text[3]}"
  end

  def get_type(file)
    if file.include? "." then
      type = file.split(".").last.upcase
    else
      type = "sem ext."
    end
    type
  end

  def take_length(path)
    $root_metadata.each do |hash|
      if hash["path"] == path then
        @length = unit(hash["bytes"])
      end
    end
    return @length
  end

  def unit(number)

    if number >= (1024**3) then
      number = number/(1024**3)
      unit = 'GB'
    elsif number >= (1024**2) then
      number = number/(1024**2)
      unit = 'MB'
    elsif number >= (1024) then
      number = number/(1024)
      unit = 'KB'
    else
      unit = 'Bytes'
    end
    units = "#{number} #{unit}"
  end

  #@param path, path of the file you want to download
  def download(path)
    $client.shares(path)
    #shareble_link = $client.shares(path)
    res = Net::HTTP.get_response(URI("#{$client.shares(path)['url']}"))
    a = "#{res['location'].to_s[0...-1]}1"
  end

  def navigation(root)
    dirs = root.split("/")
    path = Array.new

    dirs.each_with_index do |l,i|
      path << dirs[0..i].join("/")
    end
    path.delete("")
    
    return path
  end

  def get_files_metadata
    root_metadata = $client.metadata(session[:dbox_path])['contents']
    #Creates the variables to store files and directories
    files = Array.new
    directories = Array.new
    # iterate and create an array for files, for directories, creation and modification.
    root_metadata.each do |hash|
      if hash["is_dir"] == false then
        #Take all the attributes necessary to show the files informations [path, creation-time, modified-time, lenght, type]
        files << [hash["path"], date_format(hash['client_mtime']), date_format(hash['modified']), unit(hash["bytes"]),get_type(hash["path"]), hash["revision"]]
      else
        directories << hash["path"]
      end
    end
    show = [files, directories]

  end


end

app/views/authentication/_upload.html.erb
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/authentication/_upload_file.html.erb
<div class="mdl-card" id="modal">
<div>
	x
</div>
<div class="mdl-card__title mdl-card--border">
<h2 class="mdl-card__title-text"> Upload </h2>
</div>
<div class="mdl-card__subtitle-text">
	<strong>Suba um arquivo</strong> 
</div>
<%= form_tag({action: :navigation_params}, multipart: true) do %>
  <%= hidden_field_tag(:parent_id, $root) %>
  <%= hidden_field_tag(:page, $i) %>
  <%= hidden_field_tag(:fil, $files) %>
  <%= hidden_field_tag(:owner, $user.name) %>
  <div class="mdl-card__actions">
  <%= file_field_tag 'file' %> <br/>
  </div>
  <div class="mdl-card__actions">
  <%= submit_tag "Subir" %>
  </div>
<% end %>


</div>

app/views/authentication/error.html.erb
<!--NOT IN USE YET -->
<!--Login error page -->

<h1> ERRO DE LOGIN </h1>
<%= link_to("Login", root_path)%>

app/views/authentication/files.html.erb
<!-- Page that shows the files -->
<!doctype html>


<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Arquivos</title>
        
    <%= stylesheet_link_tag "https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-light_blue.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag "main" %>

    <%= javascript_include_tag "upload.js" %>
    <%= javascript_include_tag "move_file_modal.js" %>

    <%= javascript_include_tag "modernizr-2.8.3-respond-1.4.2.min.js" %>
    <%= javascript_include_tag "toggle-visibility.js" %>

    <%= javascript_include_tag "material.min.js" %>
    <%= javascript_include_tag "jquery-2.1.4.min.js" %>
    <%= javascript_include_tag "lightbox.js" %>
    <%= javascript_include_tag "dropzone.js" %>
    <%= javascript_include_tag "popup.js" %>
    <%= javascript_include_tag "application.js" %>
    
    
    

  </head>


  <body>
  
          
                  
          <div id ="main-content" class="mdl-grid mdl-grid--no-spacing">

            <div id="arquivo">
              <div class="mdl-cell mdl-cell--12-col mdl-color--indigo-900 mdl-color-text--grey-100">
              <h1>Arquivos</h1>
              <span><%= session[:dbox_path]%></span> 

          
              <nav class="mdl-navigation">
                <ul>
                  <li>
                                  
              <!--UPLOAD FILES -->  
                <%= link_to("javascript:fadeT()", :class => "mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--fab mdl-color--accent fab-top-right") do %>
                   <i class="material-icons mdl-color-text--white">file_upload</i>
                <% end%>
                    <div class="mdl-tooltip" for="btnadd1">
                      Adicionar arquivo
                    </div>
              </li>
              <!-- end -->

              <!-- CREATE FOLDER -->  
                    <li>
                
                  
                  <%# text_field_tag (:folder_name) %>
                  <%= button_to( "javascript:createFolderPopUp()", :class => "mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--fab mdl-color--accent fab-top-right", :id => "btnadd2"  ) do %>
                    <i class="material-icons mdl-color-text--white" > folder </i>
                  <% end %>

                

              <div class="mdl-tooltip" for="btnadd2">
                Adicionar pasta
              </div>
              </li>
              <!-- END -->
                  </ul>
              </nav>
          
            </div>

              <div class="mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
            <table class="mdl-data-table mdl-js-data-table mdl-color--grey-100">
              <thead>
                <tr>
                  <th></th>
                  <th>Nome</th>
                  <th>Data de Criação</th>
                  <th>Data de modificação</th>
                  <th>Tamanho</th>
                  <th>Tipo</th>
                  <th>Autor</th>
                  <th>Versões</th>

                </tr>
              </thead>
              <!-- SHOW THE DIRECTORIES AND FILES FROM DROPBOX -->
              <% @archives.each_with_index do |a,index| %>
                <tbody>
                <% if a.dir == true%>
                  <tr>

                  <%= form_tag :action => 'navigation_params', :method => 'POST' do%>
                      <%= hidden_field_tag(:parent_id, "/"+a.name+"/") %>
                    <td>
                      <%= button_tag( :type => 'submit', :class => "file-button file-name") do %>
                        <i class="material-icons" role="presentation">folder</i>
                      <% end %>
                    </td>
                    <!-- Button for enter a folder -->
                    <td> <%= button_tag( :type => 'submit', :class => "file-button file-name", :id => "#{index}") do %>
                      <%= a.name %>
                    <% end %> </td>

                    <div class="mdl-tooltip" for=<%= index %> >
                      <%= a.name %>
                    </div>

                  <% end %>

                  <td> <%= localize(a.created_at, :format => :short) %> </td><td> <%= a.updated_at[0..9] %> </td><td> </td><td> </td><td> </td><td> </td><td> </td>

                  <td>
                    <%= form_tag :action => 'remove' do%>
                      <%= hidden_field_tag(:to_remove, a.name) %>
                        <%= button_tag( :type => 'submit', :class => "mdl-button mdl-js-button mdl-button--icon mdl-button--colored", :data => {:confirm => 'Tem certeza que deseja deletar esta pasta?'}) do %>
                          <i class="material-icons">delete</i>
                        <% end %>
                    <% end %>
                  </td>
                  <td> </td>
                </tr>

              <% else %>
                <tr>
                  <td> </td>
                  <td>
                  <!-- File name -->
                  <p  class="file-name" id= <%= index%> > <%= a.name %> </p> </td> 
                    <div class="mdl-tooltip" for=<%= index %> >
                      <%= a.name %>
                    </div>

                  <td> <%= localize(a.created_at, :format => :short)%> </td>  <!-- Creation date -->
                  <td> <%= a.updated_at[0..9]%> </td>  <!-- Modification date-->
                  <td> <%# d[3] %> </td>  <!-- Size -->
                  <td> <%# d[4] %> </td>  <!-- Type -->


                  <td> <p  class="owner-name" id= <%= a.name%> > <%= @owner = a.owner %> </p> </td> <!-- Owner -->
                    <div class="mdl-tooltip" for=<%= a.name%>  >
                      <%= a.owner %>
                    </div>
                  <!-- Tamanho -->
                  <td> </td>
                  <!-- Download-->
                  <td>
                    
                    
                    <%= link_to($client.media(a.name)['url'], :class => "mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-button--colored")  do %>
                      <i class="material-icons">get_app</i>
                    <% end%>
                  </td>

                  <td>
                    <%= form_tag :action => 'remove' do%>
                      <%= hidden_field_tag(:to_remove, a.name) %>
                        <%= button_tag( :type => 'submit', :class => "mdl-button mdl-js-button mdl-button--icon mdl-button--colored") do %>
                          <i class="material-icons">delete</i>
                        <% end %>
                    <% end %>
                  </td>

                  <td> 
                    <%= link_to("javascript:movePopUp()", :class => "mdl-button mdl-js-button mdl-button--icon mdl-button--colored", :name => "move_link",:id => a.name) do %>
                      <i class="material-icons">sort</i>
                    <% end %> 
                  </td>
              <% end %>
              <% end %>
              </tbody>
              </table>
          <!-- Pages' links -->
          </div>
        </div>
      </div>    
  </body>

  <div class="mdl-card" id="modal">
  <div>
    <p id="cancel"> <%= link_to "x", "javascript:fadeT()" %> </p>
    </div>
      <div class="mdl-card__title mdl-card--border" >
        <h2 class="mdl-card__title-text"> Upload </h2>
      </div>
      <div class="mdl-card__subtitle-text">
        <strong>Suba um arquivo</strong> 
      </div>
      <div class="mdl-card__actions">
        <%= form_tag({action: :upload}, multipart: true) do %>
          <%= hidden_field_tag(:parent_id, session[:dbox_path]) %>
          <%= hidden_field_tag(:owner, current_user.name) %>
          <div class="mdl-card__actions">
          <%= file_field_tag 'file' %> <br/>
          </div>
          <div class="mdl-card__actions">
          <%= submit_tag "Subir" %>
          </div>
        <% end %>
      </div>


  </div>

  <div class="mdl-card" id="modal_to_move">
  
    <span id="cancel"> <%= link_to "x", "javascript:movePopUp()" %> </span>
  
      <div class="mdl-card__title mdl-card--border" >
        <h2 class="mdl-card__title-text"> Mover </h2>
      </div>
      
      <div class="mdl-card__actions">
        <%= form_tag({action: :move}) do %>
          <%= hidden_field_tag(:parent_id, session[:dbox_path]) %>
          <%= hidden_field_tag "page", session[:page_number] %>
          <%# hidden_field_tag(:fil, $files) %>
          <%= hidden_field_tag(:owner, current_user.name) %> 
          <%= hidden_field_tag :move_from %>  
          <div class="mdl-card__actions">
          <%= select_tag "move_to", options_for_select(Archive.where(dir: true).pluck(:name), Archive.where(dir: true).first)%>
          </div>
          <div class="mdl-card__actions">
          <%= submit_tag "mover" %>
          </div>
        <% end %>
      </div>


  </div>

    <div class="mdl-card" id="modal_to_create_folder">
  
    <span id="cancel"> <%= link_to "x", "javascript:createFolderPopUp()" %> </span>
  
      <div class="mdl-card__title mdl-card--border" >
        <h2 class="mdl-card__title-text"> Criar Pasta </h2>
      </div>
      
      <div class="mdl-card__actions">
        <%= form_tag({action: :navigation_params}, multipart: true) do %>
          <%= hidden_field_tag "parent_id", session[:dbox_path] %>
          <%= hidden_field_tag "page", session[:page_number] %>
          <%# hidden_field_tag "fil", $files %>
          <div class="mdl-card__actions">
          <%= text_field_tag "folder_name"  %>
          </div>
          <div class="mdl-card__actions">
          <%= submit_tag "Criar" %>
          </div>
        <% end %>
      </div>


  </div>


  
</html>

app/views/authentication/login.html.erb
<h1> </h1>

app/views/authentication/navigate.html.erb
<!-- FILES' AND DIRECTORIES' PAGE(DEPRECATED SINCE THE FRONT-END IMPLEMENTATION) -->

<h1>Meus arquivos </h1>
<hr/>:

<p> <% @directories.each do |d|  %>

      <%=form_tag :action => 'navigate', :method => 'POST' do%>
        <%= hidden_field_tag(:parent_id, d) %>
        <%= submit_tag d.split("/").last %>

      <% end %>
    <% end %>
</p>

<p><% @files.each do |f|%>
  <%= f.split("/").last %>  <%= link_to("Download", @client.media(f)['url']) %> <br/>
  <% end %>
</p>

app/views/authentication/navigation_params.html.erb
<!-- VIEW MADE FOR TEST -->
<h3> You are not supposed to see it </h3>

app/views/authentication/upload_error.html.erb
<!-- NOT IN USE-->
<p> Erro de upload</p> 

app/views/authentication/welcome.html.erb
<!-- WELCOME PAGE, SHOWED WHEN THE LOGIN SUCCEED -->
<h1>Bem vindo</h1>

<%= link_to "refresh", refresh_path %>