config/routes.rb
Rails.application.routes.draw do
  get 'authentication/login'
  post 'authentication/login'

  get 'authentication/welcome'
  post 'authentication/welcome'

  get 'authentication/error'
  post 'authentication/error'

  get 'authentication/navigate'
	post 'authentication/navigate'

	get 'authentication/files'
  post 'authentication/files'

	get 'authentication/navigation_params'
	post 'authentication/navigation_params'

  post 'upload' => 'authentication#upload'

  get 'refresh' => 'authentication#refresh'

  post 'rename' => 'authentication#refresh'

  post 'move' => 'authentication#move'

  post 'remove' => 'authentication#remove'
  
  get 'login1' => 'sessions#new'

  post 'sessions/create'
  
  get 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  
  get 'error' => 'sessions#error'

  root 'authentication#login'

end

app/views/layouts/application.html.erb
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<!-- Page layaout for the website as a whole -->

<%= csrf_meta_tags %>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Information Center">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Information Center</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon-192x192.png">
    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->


    <%= stylesheet_link_tag "https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-light_blue.min.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag "main" %>

    <%= javascript_include_tag "modernizr-2.8.3-respond-1.4.2.min.js" %>

  </head>
  <body>

    <!-- General -->
    <div class="layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">

      <!-- HEADER -->
      <header class="demo-header mdl-layout__header mdl-color--white mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title mdl-color-text--indigo-500">Information Center - AIESEC no Brasil</span>
          <div class="mdl-layout-spacer"></div>
          <!-- Pesquisa
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search" />
              <label class="mdl-textfield__label" for="search">Enter your query...</label>
            </div>
          </div>-->
          <span> 
            <%= form_tag(controller: :authentication, action: :files) do %> 
              <%= label_tag "Pesquisa"%>
              <%= text_field_tag "search" %>

            <% end %>
          </span>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="btninfo">
            <i class="material-icons">info</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="btninfo">
            <li class="mdl-menu__item mdl-color-text--indigo-400">Sobre</li>
            <li class="mdl-menu__item mdl-color-text--indigo-400">Contato</li>
          </ul>
        </div>
      </header>

      <!-- END HEADER -->

      <!-- Sidebar -->
      <div class="demo-drawer mdl-layout__drawer mdl-color--indigo-900 mdl-color-text--blue-grey-50">


        <!-- Profile -->
        <header class="demo-drawer-header">
          <%= image_tag(current_user.photo_url, class: "avatar") %>

          <!-- <img src="img/user.jpg" class="avatar"> -->
          <div class="avatar-name">
            <span><%= current_user.name %></span>
          </div>
        </header>
        <!-- END Profile -->

        <!-- Menu -->
        <nav id="navbar" class="demo-navigation mdl-navigation mdl-color--indigo-600">
          <!--<a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>-->
          <%# button_to '<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">folder</i>Arquivos'.html_safe, authentication_navigation_params_path, :class => "mdl-navigation__link", {:parent_id => "/", :page => 1}%>
          <%# link_to '<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">folder</i>Arquivos'.html_safe, authentication_navigation_params_path, {:parent_id => "/" , :page => 1, method: :post}, :class => "mdl-navigation__link"%>
          <%#form_tag :action => 'navigation_params', :method => 'POST', :class => "mdl-navigation__link"  do%>
            <%# hidden_field_tag(:parent_id, "/") %>
            <%# hidden_field_tag(:page, 1) %>
            <%# button_tag( '<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">folder</i>Arquivos'.html_safe, type: 'submit', :class => "mdl-navigation__link")  %>
          <%# end %>
          <%= link_to '<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">folder</i>Arquivos'.html_safe, authentication_navigation_params_path, :class =>  "mdl-navigation__link"%>
          <a class="mdl-navigation__link" href="suporte.html"><i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">help</i>Ajuda</a>
          <%= link_to '<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">exit_to_app</i>Sair'.html_safe, logout_path, :class =>  "mdl-navigation__link"%>

          <%# button_tag(logout_path, :method => :delete, :class => "mdl-layout-spacer") do %>
          <%#'<i class="mdl-color-text--blue-grey-50 material-icons" role="presentation">exit_to_app</i>Sair'.html_safe%>
          <%# end %>


          <div class="mdl-layout-spacer"></div>
          <%= image_tag("logo_aiesec.png", class: "img-rodape") %>

        </nav>
        <!-- END Menu -->
      </div>
      <!-- END Sidebar -->

      <!-- Main Content -->
      <main class="mdl-layout__content mdl-color--grey-100">
        <div id ="main-content" class="mdl-grid mdl-grid--no-spacing">
          <%= yield %>
        </div>
      </main>
      <!-- END Main Content -->
    </div>
    <!--END General -->
    <%= javascript_include_tag "material.min.js" %>
    <%= javascript_include_tag "jquery-2.1.4.min.js" %>


  </body>
</html>

app/views/layouts/login.html.erb
<!-- LOGIN LAYOUT, in this application we used a special layout for login-->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Information Center</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

       <!-- <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">-->

        <%= stylesheet_link_tag "https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-light_blue.min.css" %>
        <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" %>
        <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
        <%= stylesheet_link_tag "main" %>

        <%= javascript_include_tag "modernizr-2.8.3-respond-1.4.2.min.js" %>

    </head>
    <style type="text/css">
    body{

    background-image: url('/assets/bg.jpg');
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;

    }
    </style>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div class="layout mdl-layout mdl-js-layout">
            <main class="mdl-layout__content">
                <div class="box">
                    <div class="mdl-grid">
                            <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone">
                            <% flash.each do |key, value| %>
                             <%= content_tag :div, value, class: "flash #{key}" %>
                            <% end %>
                            <br>
                            <!-- AIESEC LOGO -->
                                <%= image_tag("logo_aiesec.png", class: "img-responsive") %>

                                <!-- FORM TO LOG -->
                                <%= form_tag :action => 'create', :controller => 'sessions' do %>
                                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col mdl-cell--4-col-phone">
                                        <%= email_field_tag 'my_email', nil, class: 'mdl-textfield__input' %>
                                        <%= label_tag 'my_email', 'Email', class: 'mdl-textfield__label'%>
                                    </div>
                                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col mdl-cell--4-col-phone">

                                        <%= password_field_tag 'my_password', nil, class: 'mdl-textfield__input' %>
                                        <%= label_tag 'my_password', 'Senha', class: 'mdl-textfield__label'%>
                                    </div>
                                    <%= button_tag("Entrar", type: 'submit', class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-cell mdl-cell--12-col mdl-button--accent mdl-color--white mdl-color-text--blue-500")%>
                                <% end %>
                                <!-- END -->


                            </div>

                    </div>
                </div>
            </main>
        </div>

        <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
        <%= javascript_include_tag "js/material.min.js" %>
        <%= javascript_include_tag "js/jquery-2.1.4.min.js" %>
        <%= javascript_include_tag "js/main.js" %>
    </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>